### ISSUE TITLE
How to change CLK behaviour

### ISSUE THREAD

**Issue by hdo** [vijaymarupudi/sph0645-pico-troubleshooting#2]
Hi,

unfortunately i'm not familiar with the PIO (yet).

Could you please describe shortly what needs to be changed to invert the CLK signal?

Thank you.

` If you'd like to use another I2S mic that actually follows the standard, toggle the 1s and 0s in the CLK signal in the .pio file.`

**Comment by vijaymarupudi** [comment]
Here's an explanation of the relevant parts of the program. Let's focus on the side bits, in bitloop1. Since this is a mono chip, it can only sample one side. As you can see, the other channel has `nop` instructions, which don't do anything, but maintain the clock signal.

The bit on the right most side of the code is the clock signal. As you can see, whenever it is zero (i.e. the signal is low), the corresponding main instruction is `in`, which means that data is sampled at that point. However, in the actual I2S standard, data should be sampled when the clock signal is high. So you need to flip all the side bits on the right most side. 0s become 1s and 1s become zeros.

Hope that helps!

```
.program i2s

.side_set 2

bitloop1:
    in pins, 1       side 0b00
    jmp x-- bitloop1  side 0b01
    in pins, 1       side 0b10
    set x, 30         side 0b11

bitloop0:
    nop       side 0b10
    jmp x-- bitloop0  side 0b11
    nop       side 0b00
public entry_point:
    set x, 30         side 0b01
```

**Comment by hdo** [comment]
That was quick. Thanks for the very detailed explanation. That helps me a lot.

Have a good one :-)

Regards,

hdo

**Comment by vijaymarupudi** [comment]
Glad I could help!
